<?php


namespace DesignByCode\Sluggable\Tests;

use Orchestra\Testbench\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{

    /**
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getApplicationPrsoviders($app)
    {
        return [DesignByCode\Sluggable\Providers\SluggableServiceProvider::class];
    }

    /**
     * Drop tables
     */
    public function tearDown() : void
    {
        \Schema::drop('posts');
    }


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $this->loadFactoriesFrom(__DIR__ . '/database/factories');

        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');

        $this->artisan('migrate', [
            '--database' => 'testbench',
            '--realpath' => realpath(__DIR__ . '/database/migrations')
        ])->run();
    }

    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);


    }

}
